apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: devhub-backendvvp-gitops-pipeline-run-init
  namespace: devhub
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    tekton.dev/pipeline: devhub-backendvvp-gitops-pipeline
    type: pipeline
spec:
  params:
    - name: source-repo
      value: 'https://github.com/devhub-mad/devhub-backendvvp-gitops.git'
    - name: source-branch
      value: main
    - name: output-image
      value: image-registry.openshift-image-registry.svc:5000/devhub/app-mod-orders/devhub-backendvvp-gitops
  pipelineRef:
    name: devhub-backendvvp-gitops-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
